### ISSUE TITLE
can't detect SHIFT_JIS

### ISSUE THREAD

**Issue by JenningsWu** [aadsm/jschardet#17]
I try to use this to detect a SHIFT_JIS file but it return {codeType: null, confidence: 0}…
I put this file [here](http://www.jenningswu.net/shiftJis.csv)

**Comment by aadsm** [comment]
Hey, sorry to get back so late to you.
I've looked into all confidence levels detected with this file and SHIFT_JIS is actually the highest one:

SHIFT_JIS confidence = 0.15602836879432624

However, this library has a minimum threshold of 0.20. Since most of the characters are numbers or non detectable SHIFT_JIS characters the confidence level is really low.
I'll add an option so you can define the minimum threshold, then you can define it before calling detect:
```javascript
jschardet.Constants.MINIMUM_THRESHOLD = 0.15;
```

**Comment by aadsm** [comment]
You should now be able to try this: https://github.com/aadsm/jschardet#options, please close this issue if it's working for you.
I'll update the npm package later.
