### ISSUE TITLE
LGPL is a license hard to work with

### ISSUE THREAD

**Issue by cynthiax** [aadsm/jschardet#37]
We are using jschardet in a corporate environment where LGPL licensed software can't be used.

We are getting errors as external-editor is pulling jschardet as dependencies instead of dev-dependency. Can we have jschardet under MIT if possible?

**Comment by marcobeierer** [comment]
Hi @cynthiax 

I'm not the author of this library, but I'm afraid this wouldn't be possible. jschardet is a port of python's chardet (https://github.com/chardet/chardet), which is licensed under LGPL and is also based on the work of another developer who has started developing the library in 2006 (or before) and already licensed the code under LGPL. From my point of view, every author of the three libraries has to acknowledge to change the license...

But is it really necessary to change the license to fulfill your corporate requirements? I have evaluated the license before I used jschardet in a project and if I understand it right, all you have to do is deliver the source code of jschardet with the license text to your clients, so that they could modify the library. You do not have to license your own code under LGPL. In a web application this shouldn't be a problem normally.

**Comment by aadsm** [comment]
Hi @cynthiax, unfortunately this is exactly as @marcobeierer described it. I don't own the copyright for the original code so I can't redistribute it under a different license. Like @marcobeierer said, this should be fine and this was one of the reasons to create the LGPL license https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License:

> The license allows developers and companies to use and integrate software released under the LGPL into their own (even proprietary) software without being required by the terms of a strong copyleft license to release the source code of their own components.

It's a big difference from GPL (which usually most companies do not want to use). However, I understand that you don't make the policy so it might be an overzealous policy in place that you can't do anything about. If I owned the original code I would definitely release it under BSD (as I've done with the other code in my github), but in this situation there's nothing I can do.

@marcobeierer, to add a bit of history, https://github.com/chardet/chardet is also a port from the original c++ code implemented at Mozilla for the Netscape browser.

**Comment by zwily** [comment]
For LGPL, my understanding is you have to make it so the end user can replace the module with another one. In the case of a webapp, you could do this by keeping it as a separate source file which the user could replace via greasemonkey/etc. However, these days it's common to bundle all your javascript together, which it seems would violate that part of the LGPL.

**Comment by dlecocq** [comment]
Would it be possible to at least upgrade the version of the license? Per https://spdx.org/licenses/LGPL-2.1.html, it looks like 2.1 has been deprecated in favor of 3. And there is a section in the license associated with `chardet` (https://github.com/chardet/chardet/blob/master/LICENSE) that addresses license versions:

> This library is free software; you can redistribute it and/or
> modify it under the terms of the GNU Lesser General Public
> License as published by the Free Software Foundation; either
> version 2.1 of the License, or (at your option) any later version.

If need be, I suppose it could probably be dual-licensed?
